# Site settings
author: kunnan #page.author > site.author> site.title
title: iosre Blog
SEOTitle: 逆向 | iosre Blog
header-img: img/post-bg-desk.jpg # 设置默认的封面图片
email: zhang_kn@icloud.com
description: "https://zhangkn.github.io/"
keyword: "iosre, kunnan Blog, 张坤楠的博客, zhangkunnan, zhangkn.github.io, iOS, 逆向, ReverseEngineering"
url: "https://kunnan.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/kunnan/kunnan.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "https://zhangkn.github.io/"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# RSS: false
weibo_username:     602056727
zhihu_username:     kunnan
github_username:    kunnan
facebook_username:  zhangkn
jianshu_username:   0c4325829de0
twitter_username:   zhangkunnan
linkedin_username: iosre

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# 配置文件_config.yml中，使用了 plugins 的配置项，应该是用 plugins 替换掉gems。
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统 https://disqus.com/admin/create/ 
# Disqus（https://disqus.com/） Your unique disqus URL will be: kunnan.disqus.com
# https://kunnan.disqus.com/admin/install/subscription/
# https://kunnan.disqus.com/admin/install/platforms/jekyll/
# ---
# layout: default
# comments: true
# # other options
# ---
# In between a {% if page.comments %} and a {% endif %} tag, copy and paste the Universal Embed Code in the appropriate template where you'd like Disqus to load.

# https://kunnan.disqus.com/admin/install/platforms/universalcode
# s.src = 'https://kunnan.disqus.com/embed.js';
# How to display comment count
# <script id="dsq-count-scr" src="//kunnan.disqus.com/count.js" async></script>
# 
# Your website shortname is kunnan.

disqus_username: kunnan

# Gitalk https://github.com/settings/applications/new
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 3bd49355dd00601577d9                            #生成的clientID Github Application clientID
  clientSecret: f953419ad4ce96ba4bf16d98493ddfe8fd6cf5b4    #生成的clientSecret Github Application clientSecret
  repo: kunnan.github.io    #仓库名称 存储你评论 issue 的 Github 仓库名
  owner: kunnan    #github用户名
  admin: zhangkn #Github 用户名  //这个仓库的管理员，可以有多个，用数组表示，一般写自己,
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
# id 页面的唯一标识，gitalk会根据这个标识自动创建的issue的标签  我们使用页面的相对路径作为标识

# 统计

# Analytics settings
# Baidu Analytics https://tongji.baidu.com/web/welcome/login
# https://tongji.baidu.com/sc-web/24849807/home/site/getjs?siteId=11929988
# https://tongji.baidu.com/sc-web/24849807/home/js/check?siteId=11929988
ba_track_id: 508241b4b7829bcc7d10f4c0006a1bb9
# https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fzhangkn.github.io%2F&hl=zh-CN&query=!openapplicationwithbundleid
# https://www.google.com/webmasters/tools/home?utm_source=search_console&utm_campaign=add-property&pli=1
# Google Analytics
# https://www.google.com/analytics/
# https://www.google.com/webmasters/tools/dashboard?siteUrl=https://zhangkn.github.io/
# https://analytics.google.com/analytics/web/?hl=zh-CN&pli=1#/a111030597w165618623p166148021/admin/property/create
# 创建新媒体资源后，您将可以获得一个跟踪 ID。
# https://analytics.google.com/analytics/web/?hl=zh-CN&pli=1#/a111030597w174737082p173885891/admin/tracking/tracking-code/

# https://www.google.com/webmasters/tools/analytics-site-selection?hl=zh_CN&property=174737082&continue=https%3A%2F%2Fanalytics.google.com%2Fanalytics%2Fweb%2F%3Fhl%3Dzh-CN%26pli%3D1%23%2Fa111030597w174737082p173885891%2Fadmin%2Fintegrations%2Fwmx
# https://www.google.com/webmasters/verification/home?hl=zh-CN&theme=wmt&continue=https://www.google.com/webmasters/tools/dashboard?hl%3Dzh-CN%26sig%3DALjLGbM42SIgAoHv_pXtJC1WuduIPcy_bw&pli=1
# https://www.google.com/webmasters/tools/message-view?hl=zh-CN&authuser=0&message-filter=all&grid.r=0&msgid=AB9YKzL8eZsURMO_HzZFjCi9M7T6Zm_7DVpIHgp0Rt4AQkgLTkCiFiF4p93x5tHhubqz1A8sWYVYYLMtv7jIeqz3TdX7WgpSsg

# - [xmlsitemapgenerator 站点地图](https://xmlsitemapgenerator.org/free/waiting.aspx?job=8b793801-6086-4d18-976a-5e8c004c2bd7)
# https://xmlsitemapgenerator.org/sitemap-generator.aspx
# https://www.google.com/webmasters/verification/details?hl=zh-CN&siteUrl=https://kunnan.github.io/
ga_track_id: 'UA-111030597-2'            # Format: UA-xxxxxx-xx UA-111030597-2
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends:   
friends: [
    {
        title: "github Pages",
        href: "https://zhangkn.github.io/tags/"
    },{
        title: "iosre",
        href: "http://iosre.com/u/zhangkn/activity"
    },{
        title: "csdn",
        href: "https://blog.csdn.net/z929118967"
    },{
        title: "segmentfault",
        href: "https://segmentfault.com/u/zhangkunnan"
    },{
        title: "cocoapods",
        # href: "https://cocoapods.org/owners/30966"//https://cocoapods.org/pods/KNPodlib
        href: "https://cocoapods.org/pods/KNPodlib"
    },{
        title: "gist.github.com",
        href: "https://gist.github.com/zhangkn/"
    }
    ,{
        title: "CocoaPods Specs",
        href: "https://github.com/zhangkn/Specs.git"
    }
    ,{
        title: "flexbox-playground",
        href: "https://cssflex.github.io/"
    } ,{
        title: "tumblr",
        href: "https://kunnanblr.tumblr.com/"
    }
]